services:
  hive:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"

  postgres:
    image: postgres:latest
    container_name: pg_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    volumes:
      - postgres-data:/var/lib/postgresql/data


  minio:
    image: minio/minio:latest
    container_name: minio_service
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"


  trino-coordinator:
    image: "trinodb/trino:455"
    # container_name: trino_coordinator
    ports:
      - '8089:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    depends_on:
      - hive
      - trino-worker


  trino-worker:
    image: "trinodb/trino:455"
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
    depends_on:
      - hive
    deploy:
      mode: replicated
      replicas: 1


  superset:
    build: ./superset
    container_name: superset_service
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset-data:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local
  superset-data:
    driver: local
